### PR TITLE
Slightly nicer error message when a body is all definitions.

### PR DESCRIPTION
**Pull request by stamourv**
Currently, this program:
```
#lang dssl2
def foo():
    def bar():
        3
```
raises an error in terms of the Racket expansion.

The PR catches these kinds of errors, and produces a slightly nicer error message.

Two issues that remain:
- I couldn't get it to print the actual DSSL2 surface syntax where the error is, but rather the AST version.
- I didn't add the above program as a test; do you have tests for syntax errors? I didn't find any.

### CODE REVIEW

**Comment by tov** [comment]
I don't think I do have syntax error tests…

**Comment by tov** [comment]
Is it necessarily wrong to end with a definition? Instead of improving this error message, maybe we should make the result `None` in that case.

**Comment by stamourv** [comment]
Is there a non-mistake situation where you have definitions, but no expression in the body?
I'd imagine that that error would catch a lot of oversights, e.g., missing recursing starting point.

**Comment by tov** [comment]
It’s never ultimately useful, but there are definitely cases where you could temporarily have a definition last in a block. And notably, Python allows it.

**Comment by stamourv** [comment]
Alright, either way works for me.
The more time-sensitive PR is the other one anyway. Any ETA on that one?

**Comment by tov** [comment]
So it turns out it wasn’t just `def` that did this—`let`-with-no-RHS, `struct`, `class`, and `interface` did as well. I implemented my solution on a branch, [block-end-fix](https://github.com/tov/dssl2/tree/block-end-fix). If you’re happy with that then I’ll merge it.

**Comment by stamourv** [comment]
That looks fine, I'm happy with that.
No tests?

**Comment by tov** [comment]
Yeah, okay, a couple tests.

**Pull request closed without merging**
